// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"coin/internal/biz"
	"coin/internal/conf"
	"coin/internal/data"
	"coin/internal/server"
	"coin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	coinRepo := data.NewCoinRepo(dataData, logger)
	coinOptcase := biz.NewCoinOptcase(coinRepo, logger)
	coinService := service.NewCoinService(coinOptcase, logger)
	httpServer := server.NewHTTPServer(confServer, coinService, logger)
	grpcServer := server.NewGRPCServer(confServer, coinService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
