// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoinClient is the client API for Coin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoinClient interface {
	AddCoin(ctx context.Context, in *AddCoinRequest, opts ...grpc.CallOption) (*AddCoinReply, error)
	ReduceCoin(ctx context.Context, in *ReduceCoinRequest, opts ...grpc.CallOption) (*ReduceCoinReply, error)
	ShowCoin(ctx context.Context, in *ShowCoinRequest, opts ...grpc.CallOption) (*ShowCoinReply, error)
}

type coinClient struct {
	cc grpc.ClientConnInterface
}

func NewCoinClient(cc grpc.ClientConnInterface) CoinClient {
	return &coinClient{cc}
}

func (c *coinClient) AddCoin(ctx context.Context, in *AddCoinRequest, opts ...grpc.CallOption) (*AddCoinReply, error) {
	out := new(AddCoinReply)
	err := c.cc.Invoke(ctx, "/api.coin.v1.Coin/AddCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) ReduceCoin(ctx context.Context, in *ReduceCoinRequest, opts ...grpc.CallOption) (*ReduceCoinReply, error) {
	out := new(ReduceCoinReply)
	err := c.cc.Invoke(ctx, "/api.coin.v1.Coin/ReduceCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) ShowCoin(ctx context.Context, in *ShowCoinRequest, opts ...grpc.CallOption) (*ShowCoinReply, error) {
	out := new(ShowCoinReply)
	err := c.cc.Invoke(ctx, "/api.coin.v1.Coin/ShowCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoinServer is the server API for Coin service.
// All implementations must embed UnimplementedCoinServer
// for forward compatibility
type CoinServer interface {
	AddCoin(context.Context, *AddCoinRequest) (*AddCoinReply, error)
	ReduceCoin(context.Context, *ReduceCoinRequest) (*ReduceCoinReply, error)
	ShowCoin(context.Context, *ShowCoinRequest) (*ShowCoinReply, error)
	mustEmbedUnimplementedCoinServer()
}

// UnimplementedCoinServer must be embedded to have forward compatible implementations.
type UnimplementedCoinServer struct {
}

func (UnimplementedCoinServer) AddCoin(context.Context, *AddCoinRequest) (*AddCoinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCoin not implemented")
}
func (UnimplementedCoinServer) ReduceCoin(context.Context, *ReduceCoinRequest) (*ReduceCoinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReduceCoin not implemented")
}
func (UnimplementedCoinServer) ShowCoin(context.Context, *ShowCoinRequest) (*ShowCoinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowCoin not implemented")
}
func (UnimplementedCoinServer) mustEmbedUnimplementedCoinServer() {}

// UnsafeCoinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoinServer will
// result in compilation errors.
type UnsafeCoinServer interface {
	mustEmbedUnimplementedCoinServer()
}

func RegisterCoinServer(s grpc.ServiceRegistrar, srv CoinServer) {
	s.RegisterService(&Coin_ServiceDesc, srv)
}

func _Coin_AddCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).AddCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.coin.v1.Coin/AddCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).AddCoin(ctx, req.(*AddCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_ReduceCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).ReduceCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.coin.v1.Coin/ReduceCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).ReduceCoin(ctx, req.(*ReduceCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_ShowCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).ShowCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.coin.v1.Coin/ShowCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).ShowCoin(ctx, req.(*ShowCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coin_ServiceDesc is the grpc.ServiceDesc for Coin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.coin.v1.Coin",
	HandlerType: (*CoinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCoin",
			Handler:    _Coin_AddCoin_Handler,
		},
		{
			MethodName: "ReduceCoin",
			Handler:    _Coin_ReduceCoin_Handler,
		},
		{
			MethodName: "ShowCoin",
			Handler:    _Coin_ShowCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/coin/v1/coin.proto",
}
